basic.forever(function () {
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 40)
    basic.pause(5000)
    maqueen.motorStop(maqueen.Motors.All)
    basic.pause(2000)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 40)
    basic.pause(5000)
    maqueen.motorStop(maqueen.Motors.M1)
    basic.pause(2000)
})
